### ISSUE TITLE
"Error: InvalidFont" on Fedora 36 Workstation

### ISSUE THREAD

**Issue by JamesFrederik** [trimental/inlyne#59]
I get the the response 

"Error: InvalidFont"

when running for example $inlyne README.md

after installing via the cargo command on Fedora 36 Workstation.

I'm guessing it's related to fontconfig?

**Comment by CosmicHorrorDev** [comment]
I'm struggling getting virtualbox to run a Fedora VM

Can you still reproduce if you specify the fonts in `inlyne`'s config file. The config is located at `~/.config/inlyne/inlyne.toml` by default. Here is the font portion from mine

```toml
[font-options]
regular-font = "DejaVu Sans"
monospace-font = "Iosevka"
```
