### ISSUE TITLE
Bug: Droid Sans font can render incorrectly

### ISSUE THREAD

**Issue by coastalwhite** [trimental/inlyne#79]
Running `inlyne README.md` without any additional specification does not properly load a font. I am going to guess this is a bug in an upstream dependency, but it might be valuable to track that here as well.

# Screenshot
![image](https://user-images.githubusercontent.com/6944009/236688724-8ffe5c32-a751-4220-9330-32a0635e8425.png)

No errors are shown and the default configuration is used.

**Comment by coastalwhite** [comment]
Just for some added context. It is loading the system fonts in the `fonts::select_best_font` function.

**Comment by trimental** [comment]
Hmm that's unfortunate, font loading is definitely one of those things where "it works on my machine" I'll try to look into this.

**Comment by CosmicHorrorDev** [comment]
@coastalwhite We cache the selection, so you can find out what it's trying to load by looking at in your cache home (`~/.cache/inlyne/font_regular.toml`). I have my font set to Fira Sans, so I get this

```toml
name = "Fira Sans"

[base]
path = "/usr/share/fonts/TTF/FiraSans-Regular.ttf"
binary = false
font_index = 0

[italic]
path = "/usr/share/fonts/TTF/FiraSans-Italic.ttf"
binary = false
font_index = 0

[bold]
path = "/usr/share/fonts/TTF/FiraSans-Bold.ttf"
binary = false
font_index = 0

[bold_italic]
path = "/usr/share/fonts/TTF/FiraSans-BoldItalic.ttf"
binary = false
font_index = 0
```

Could see if it's picking up a weird font on your system for some reason

**Comment by coastalwhite** [comment]
I did manage to resolve the problem by using a different font. I was using `Droid Sans` and `Droid Mono` before. These did not work. Switching to `Arial` and `Jetbrains Mono` solved the problem. I am guessing there is some issue in `glyph_brush` with this font.

**Comment by coastalwhite** [comment]
It does not create a `.cache` file for me, btw @CosmicHorrorDev. I looked through the code and saw that it does not said these sometimes. I guess my system was that one.

**Comment by CosmicHorrorDev** [comment]
Huh, I can also reproduce this issue with `Droid Sans`. It seems to only be the base font and italics that have issues which is selecting a different font for me than bold and bold+italics

```toml
name = "Droid Sans"

[base]
path = "/usr/share/fonts/droid/DroidSansGeorgian.ttf"
binary = false
font_index = 0

[italic]
path = "/usr/share/fonts/droid/DroidSansGeorgian.ttf"
binary = false
font_index = 0

[bold]
path = "/usr/share/fonts/droid/DroidSans-Bold.ttf"
binary = false
font_index = 0

[bold_italic]
path = "/usr/share/fonts/droid/DroidSans-Bold.ttf"
binary = false
font_index = 0
```
